apiVersion: lambda.aws.upbound.io/v1beta1
kind: Function
metadata:
  annotations:
    meta.upbound.io/example-id: lambda/v1beta1/function
    uptest.upbound.io/timeout: "3600"
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    handler: lambda_function.lambda_handler
    #packageType: Zip
    region: us-east-1
    runtime: python3.9
    #s3Bucket: upbound-provider-test-data
    s3Key: hello-python.zip
    timeout: 60
    role: arn:aws:iam::626109959667:role/service-role/testetest-role-rdxlo58r
